# Generated by Django 4.1.7 on 2023-04-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pathImage', models.CharField(max_length=100)),
                ('uploader', models.CharField(max_length=100)),
            ],
        ),
    ]
