# Generated by Django 4.2 on 2023-04-04 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ximage_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='ximage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
