# Generated by Django 4.1.7 on 2023-04-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ximage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ximage',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
    ]
