# Generated by Django 4.2 on 2023-04-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ximage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ximage',
            name='title',
        ),
    ]
