# Generated by Django 4.2 on 2023-04-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ximage_published_ximage_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ximage',
            name='published',
        ),
        migrations.RemoveField(
            model_name='ximage',
            name='updated',
        ),
    ]
