# Generated by Django 4.2 on 2023-04-08 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_ximage_published_remove_ximage_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSegmentationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pathSegmentationKMeans', models.CharField(max_length=100)),
                ('pathSegmentationAdaptive', models.CharField(max_length=100)),
                ('pathGroundTruth', models.CharField(max_length=100)),
                ('report', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ximage')),
            ],
        ),
    ]
