# Generated by Django 4.2.1 on 2023-05-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_xsegmentationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiCanny',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiPrewitt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xsegmentationresult',
            name='pathDeteksiTepiSobel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xsegmentationresult',
            name='pathSegmentationOtsu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
